### ISSUE TITLE
Some IEDs are rejecting commands and are crashing/rebooting after receiving iec61850 command from json scada iec61850-client driver.

### ISSUE THREAD

**Issue by arifmjcet** [riclolsen/json-scada#143]
Hi Ricardo, I would like to share the issue we faced while sending commands to IEDs using iec61850 client driver.  Some IEDs of ABB/ Hitachi make are getting crashed after receiving  commands from jsonscada-iec61850-client driver but  executing commands correctly  with  other iec61850 client softwares. Upon inspecting code in MongoCommands.cs file, in line 243, origin identifier string is set as Copyright Message string defined in the code. This is too long and some IEDs are rejecting the commands and rebooting/crashing. After replacing the origin-identifier with a shorter string like "jsonScada", the above problem was resolved.

**Comment by riclolsen** [comment]
Thanks @arifmjcet, I will update the code.
