### ISSUE TITLE
What is the license of the product?

### ISSUE THREAD

**Issue by joyshmitz** [riclolsen/json-scada#2]
in some project files, there is a header,
"* DNP3 Client Protocol driver for {json: scada}
  * {json: scada} - Copyright (c) 2020 - Ricardo L. Olsen
  * This file is part of the JSON-SCADA distribution (https://github.com/riclolsen/json-scada).
  * This program is free software: you can redistribute it and / or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation, version 3. "

 and some do not - (src/dnp3/Dnp3Client/Dnp3Client.sln)

the license section in the readme.md file is not obvious

p.s.
as a suggestion, can you put the license file in the project root.
Sounds trivial, but clarifies a lot.

**Comment by riclolsen** [comment]
It is GPL3.
Thanks for the suggestion I will include a global license file.
