### ISSUE TITLE
why in tabular some alarms look normal, others are inactive and without timestamps

### ISSUE THREAD

**Issue by joyshmitz** [riclolsen/json-scada#22]
![tabular-alarm-missing-t-stamp2021-03-22](https://user-images.githubusercontent.com/11138019/112111654-2a518f00-8bbd-11eb-875d-998943ddc2ff.png)

**Comment by riclolsen** [comment]
Those that are dimmed are already acknowledged by operators, they are considered persistent for being at the defined alarm state.
