### ISSUE TITLE
How to increase tooltip preview of screen? Now we have some cut at it's edge:

### ISSUE THREAD

**Issue by joyshmitz** [riclolsen/json-scada#23]
![2021-03-23](https://user-images.githubusercontent.com/11138019/112269016-7fa2a480-8c80-11eb-80a9-bfe87c5dcb6b.png)

**Comment by riclolsen** [comment]
You can use 

Popup Tab with Source =  "preview:display.html?SVGFILE=svg/filename.svg&HIDETB=1"

“preview:URL”: presents a preview of the URL when the mouse is over the object. The width and height parameters define the preview window size.

I will also make the default preview size configurable.

**Comment by joyshmitz** [comment]
thanks for help

**Comment by riclolsen** [comment]
After changes can be also done with Open Tab
See
https://github.com/riclolsen/json-scada/blob/master/src/svg-display-editor/README.md#open-tab
Added also config options on config_viewers.js to set default size and internal zoom.
