### ISSUE TITLE
How to feed back commands sent from views?

### ISSUE THREAD

**Issue by Drincann** [riclolsen/json-scada#35]
I have configured the command point in the realtimedata collection, and can send the command from the view. 

I also received the command using my sparkplug program and made the action I need. 

However, after sending commands in the view, the response of the view is different from that of your online demo. It seems that your online demo receives a response from the mqtt device and displays "OK", while my view displays "???", It's like this:

My demo:

![image](https://user-images.githubusercontent.com/53897259/125720624-1d560d0a-c33e-40d7-a93b-d7c28bc0f886.png)

Your online demo:

![image](https://user-images.githubusercontent.com/53897259/125720688-61dc56f5-bb13-4644-be82-4d5bd13723a1.png)

In all the documents you provided, I only found the following related content:

[ https://github.com/riclolsen/json-scada/blob/master/docs/schema.md ]( https://github.com/riclolsen/json-scada/blob/master/docs/schema.md )

> # commandsQueue collection
> This collection has no configuration, it is written by the system when user issue commands in the UI. Commands are inserted here to be dispatched by protocols drivers. **_Protocol acknowledgement information is updated here also by protocol drivers._**

The last sentence seems to be the key point. How to feed back to the system that I have received and successfully executed the command so that it can be displayed on the view like your online demo.

**Comment by riclolsen** [comment]
Yes, feedback on vanilla MQTT and Sparkplug commands was missing.
I have updated the code for the MQTT driver to fix this problem.
Thank you very much for spotting this problem!
