### ISSUE TITLE
New tag will not be processed by cs_data_processor.

### ISSUE THREAD

**Issue by Drincann** [riclolsen/json-scada#38]
Hello.

When I created a new label on the admin page and configured it, sending data to the mqtt subject of the new label did not work.

I checked the realtimeData collection of mongo db and confirmed that the sourceDataUpdate field of this collection has been written with the data I just sent, which shows that the sparkplug-mqtt module is working properly.

So I went to debug the cs_data_processor module and found that the data update of the new label did not trigger the change event of the changeStream of cs_data_processor, so I saw this piece of code. It seems that one condition that triggers the change event is that the tag has a value field.

`json-scada/src/cs_data_processor/cs_data_processor.js`:
![image](https://user-images.githubusercontent.com/53897259/128327932-1c1b3d9b-da49-4e9f-ae04-170451894ee6.png)

I noticed that creating a new tag is achieved through the /Invoke/auth/createTag route of server_realtime_auth.

`json-scada/src/server_realtime_auth/app/controllers/auth.controller.js`:
![image](https://user-images.githubusercontent.com/53897259/128327828-4a766fbc-c555-4074-89f9-9704b1564d69.png)

But the mongooseSchema used by this route does not contain the value field.

`json-scada/src/server_realtime_auth/app/models/tag.model.js`:
![image](https://user-images.githubusercontent.com/53897259/128327728-d96fb15a-168b-44ee-a5a2-bd189fcd465d.png)

Is the reason for the missing value field because of my wrong way of using it?

Did I miss something?

Thank you!

**Comment by riclolsen** [comment]
It was missing the value field and many others.
I've committed the fixes now.
Great contribution, thanks.
