### ISSUE TITLE
base demo monitoring 

### ISSUE THREAD

**Issue by joyshmitz** [riclolsen/json-scada#4]
![monitoring-stack](https://user-images.githubusercontent.com/11138019/94982086-53fbf880-0540-11eb-859a-653b473da8cf.png)
please see an example for a your demo-docker
- grafana container in the docker-compose.yaml stack commented out
- raised the stack for monitoring
[monitor stack ](http://130.61.218.49:3000)
login admin
passwd jsonscada

next  Features: ()

- MongoDB Server Status metrics (cursors, operations, indexes, storage, etc)
- MongoDB Replica Set metrics (members, ping, replication lag, etc)
- MongoDB Replication Oplog metrics (size, length in time, etc)
- MongoDB Sharding metrics (shards, chunks, db/collections, balancer operations)
- MongoDB RocksDB storage-engine metrics (levels, compactions, cache usage, i/o rates, etc)
- MongoDB WiredTiger storage-engine metrics (cache, blockmanger, tickets, etc)
- MongoDB Top Metrics per collection (writeLock, readLock, query, etc*)

**Comment by riclolsen** [comment]
This is great, nice job! It can provide many insights on deployments.
Also, Mongo monitoring is crucial. Looking forward to seeing that too.
Maybe we can include this in the Docker demo.

**Comment by joyshmitz** [comment]
Thank you very much, I'm working on monitoring Mongodb. I will test it and give it to you for inclusion in the demo.
I am thinking about two versions, the first is simplified what you saw, the second for production.
For example, we will monitor 4 servers / hosts
* Server {1,2} .domain.com - staging server
* Server {3,4} .domain.com - production server
